tap "buo/cask-upgrade"
tap "github/gh"
tap "hashnode/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ravenac95/sudolikeaboss"
tap "vitorgalvao/tiny-scripts"
brew "awscli@1", link: true
brew "bash-completion"
brew "bat"
brew "cabextract"
brew "exercism"
brew "fd"
brew "libpng"
brew "freetype"
brew "fzf"
brew "gh"
brew "jpeg"
brew "git"
brew "gnutls"
brew "libassuan"
brew "gnupg"
brew "htop"
brew "imagemagick"
brew "lastpass-cli"
brew "mas"
brew "nsnake"
brew "nvm"
brew "prettyping"
brew "ruby-build"
brew "rbenv"
brew "shpotify"
brew "trash"
brew "tree"
brew "wimlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "1password-cli"
cask "appcleaner"
cask "balenaetcher"
cask "chromium"
cask "cyberduck"
cask "discord"
cask "docker"
cask "droplr"
cask "firefox"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-hasklig"
cask "font-iosevka"
cask "font-source-code-pro"
cask "github"
cask "google-chrome"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "logitech-options"
cask "macdown"
cask "mark-text"
cask "onyx"
cask "openoffice"
cask "openvpn-connect-beta"
cask "paintbrush"
cask "pluralsight"
cask "postman"
cask "qmk-toolbox"
cask "rocket"
cask "sequel-pro"
cask "silverlight"
cask "slack"
cask "soundflower"
cask "soundflowerbed"
cask "spotify"
cask "tableplus"
cask "the-unarchiver"
cask "vanilla"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zeplin"
mas "Keynote", id: 409183694
mas "LittleIpsum", id: 405772121
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SonicWall Mobile Connect", id: 822514576
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
